version : '3.7'
services :
  ui:
    build: 
      context: ./fullstack
    depends_on:
      - employeeService
    image: angular_img 
    container_name : ui_container
    ports: 
      - 80:80
    networks:
      front_end:
      
  employeeService:
    build: 
      context: ./springComplete
    depends_on:
      - databaseservice
    image: springcomplete_img 
    container_name : employee_api
    domainname: employee_api
    ports: 
      - 8080:8080
    networks:
      front_end:
      back_end :
          
  databaseservice:
    image: mysql:5.6
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: ems
    volumes:
        -  mysql_vol2:/var/lib/mysql
        - ./mysqlProj:/docker-entrypoint-initdb.d
    networks:
      back_end:

volumes: 
  mysql_vol2:

networks:
  front_end:
   ipam:
    driver: default
    config:
     - subnet: 172.26.0.0/16
  back_end:
  
  